twig:
    file_name_pattern: '*.twig'

    # la propriÃ©tÃ© form_themes permet de choisir le modÃ¨le de construction des formulaires html
    form_themes: ["bootstrap_4_layout.html.twig"]

    # la propriÃ©tÃ© 'globals' permet de crÃ©er des variables globales (âš  la valeur ne peut Ãªtre variable)
    globals:
        chemin_images: "/img/"
        chemin_couvertures: "/img/couvertures/"
    
    # la propriÃ©tÃ© 'date' va permettre de configurer le format par dÃ©faut du filtre 'date'
    date:
        format: d/m/Y

    # ğŸ’¬  disabled Sf7
    autoescape: false




when@test:
    twig:
        strict_variables: true
